name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: v1/${{ runner.os }}/pip/${{ hashFiles('**/{requirements,development}.txt') }}
          restore-keys: v1/${{ runner.os }}/pip/
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-18/${{ hashFiles('**/package-lock.lock') }}
          restore-keys: v1/${{ runner.os }}/node-18/
      - name: Run tests
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "make test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
